### ISSUE TITLE
What is the command-line for eqn2jed?

### ISSUE THREAD

**Issue by oboroc** [necroware/sbcms#1]
Hi, thanks for publishing this! Please add the command-line for eqn2jed. As someone who never worked with GALs before, it took me a while to figure out.

I found OPAL Jr 2.1 zip archive, extracted it and ran this command-line:

    eqn2jed.exe sbcms.eqn -osbcms.jed -dG16V8A

Also, please consider uploading compiled sbcms.jed to your repository, it would simplify life for folks who just want to play with CMS music on Sound Blaster 2.0.

**Comment by necroware** [comment]
Hi, thank you! I'll add the line into the documentation. I didn't upload JED file because of licensing reasons. OPALjr is not free software and I don't know, if I violate some copy right publishing this. That's why I also didn't say, where to download the compiler.... Furthermore, I guess, everybody, who is able to write a GAL will be also curious to know how to create a JED from EQN on their own ;)

**Comment by necroware** [comment]
BTW, the compilation line is actually much simpler:
eqn2jed.exe sbcms.eqn

the information about the GAL is already in the EQN and the output file is derived from the input file automatically....

**Comment by oboroc** [comment]
Huh! It works for me too: `eqn2jed.exe sbcms.eqn`, but it didn't when I tried first time. I must have had a typo somewhere.

You don't have to tell anyone where to buy OPALjr software, just how to use it.

As I understand, eqn2jed parses eqn file, then interprets it and runs all possible inputs and records resulting outputs to jed file. Obviously restriction on what GAL pins can do what help. But it doesn't sound like an impossible project to re-implement in some modern language like Python or Go or whatever :) Not asking you to do it, just musing about it.

**Comment by necroware** [comment]
Yes, one open source project exists, but it is buggy and is missing some features and is not (fully) compatible to OPALjr code. I have some improvements in mind and already started to write own compiler for this in C++, however didn't have enough time yet to make it. Currently I have a parser, but no code generator yet. May be one day.... currently I'm working on too many projects simultaneously..... :D

**Comment by TzOk83** [comment]
There is WinCUPL which is freeware... however, the source format is slightly different. JED output format is a JEDEC format, which I believe is also free.

**Comment by theos10** [comment]
This is the rev 0.6 WinCUPL Format :
[MCEPLUG.txt](https://github.com/user-attachments/files/17704068/MCEPLUG.txt)
rename it with .PLD extention. and build it with WinCUPL

**Comment by necroware** [comment]
Meanwhile the compiled file is included in the release, so you don't need to compile anything:
https://github.com/necroware/sbcms/releases/tag/20190410
